
name: compute involvement degree

on: [push]
    
jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # 指定python版本
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      - name: Display involvement degree
        run: python .\scores.py ${{ secrets.GITHUB_TOKEN }} # 执行