
name: compute involvement degree

on: [push]
    
jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - name: Update git version
        run: |
          sudo apt-get install -y software-properties-common \
            && sudo apt-get update \
            && sudo add-apt-repository -y ppa:git-core/ppa \
            && sudo apt-get update \
            && sudo apt-get install -y git
      - uses: actions/checkout@v4
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # 指定python版本
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests gitpython
      - name: Display involvement degree
        working-directory: ${{ github.workspace }}
        run: python scores.py -t ${{ secrets.GITHUB_TOKEN }} # 执行